/*
 * SPDX-FileCopyrightText: 2026 ESP32-S3 USB DAC Project
 * SPDX-License-Identifier: MIT
 */

#ifndef _OTA_UI_HTML_H_
#define _OTA_UI_HTML_H_

static const char s_ota_ui_html[] = "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,user-scalable=no\">\n"
"<title>// DSP32-S3 // FIRMWARE OTA UPDATE //</title>\n"
"<style>\n"
":root{\n"
"  --bg:#000000;\n"
"  --fg:#ffffff;\n"
"  --dim:#666666;\n"
"  --faint:#222222;\n"
"  --mono:ui-monospace,'Courier New',Consolas,monospace;\n"
"}\n"
"*{box-sizing:border-box;margin:0;padding:0}\n"
"body{\n"
"  background:var(--bg);\n"
"  color:var(--fg);\n"
"  font-family:var(--mono);\n"
"  font-size:12px;\n"
"  line-height:1.4;\n"
"  padding:16px;\n"
"  max-width:760px;\n"
"  margin:0 auto;\n"
"  letter-spacing:1px;\n"
"}\n"
"a{color:var(--fg);text-decoration:none;transition:background .1s,color .1s}\n"
"header{\n"
"  display:flex;\n"
"  justify-content:space-between;\n"
"  align-items:center;\n"
"  border:1px solid var(--fg);\n"
"  padding:12px 14px;\n"
"  margin-bottom:14px;\n"
"  gap:10px;\n"
"}\n"
"h1{\n"
"  font-size:14px;\n"
"  font-weight:700;\n"
"  letter-spacing:2px;\n"
"  text-transform:uppercase;\n"
"  display:flex;\n"
"  align-items:center;\n"
"  gap:10px;\n"
"}\n"
".badge{\n"
"  font-size:10px;\n"
"  padding:2px 6px;\n"
"  border:1px solid var(--fg);\n"
"  background:#000;\n"
"  color:var(--fg);\n"
"  text-transform:uppercase;\n"
"}\n"
".section{\n"
"  border:1px solid var(--fg);\n"
"  padding:14px;\n"
"  margin-bottom:14px;\n"
"  background:#000;\n"
"}\n"
".sec-title{\n"
"  font-size:11px;\n"
"  text-transform:uppercase;\n"
"  letter-spacing:2px;\n"
"  margin-bottom:12px;\n"
"  padding-bottom:6px;\n"
"  border-bottom:1px solid var(--faint);\n"
"  color:var(--fg);\n"
"}\n"
".info-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:10px;margin-bottom:8px}\n"
".info-item{\n"
"  background:#000;\n"
"  border:1px solid var(--dim);\n"
"  padding:10px;\n"
"  font-family:var(--mono);\n"
"  font-size:11px;\n"
"}\n"
".info-lbl{color:var(--dim);margin-bottom:4px;font-size:10px;text-transform:uppercase}\n"
".drop-zone{\n"
"  border:1px dashed var(--fg);\n"
"  padding:32px 16px;\n"
"  text-align:center;\n"
"  cursor:pointer;\n"
"  background:#000;\n"
"  transition:all .15s;\n"
"}\n"
".drop-zone.hover{\n"
"  background:var(--fg);\n"
"  color:var(--bg);\n"
"}\n"
".drop-zone.hover div{color:var(--bg)!important}\n"
"button, .btn{\n"
"  background:#000000;\n"
"  border:1px solid var(--fg);\n"
"  color:var(--fg);\n"
"  padding:8px 16px;\n"
"  font-family:var(--mono);\n"
"  font-size:11px;\n"
"  font-weight:700;\n"
"  letter-spacing:1px;\n"
"  cursor:pointer;\n"
"  border-radius:0;\n"
"  text-transform:uppercase;\n"
"  outline:none;\n"
"  transition:background .1s,color .1s;\n"
"}\n"
"button:hover, .btn:hover{\n"
"  background:var(--fg);\n"
"  color:var(--bg);\n"
"}\n"
".btn:disabled{opacity:0.3;cursor:not-allowed}\n"
".progress-wrap{\n"
"  height:14px;\n"
"  background:#000;\n"
"  border:1px solid var(--fg);\n"
"  margin-top:12px;\n"
"  display:none;\n"
"  overflow:hidden;\n"
"}\n"
".progress-bar{\n"
"  height:100%;\n"
"  width:0%;\n"
"  background:var(--fg);\n"
"  transition:width .1s linear;\n"
"}\n"
".log-box{\n"
"  background:#000;\n"
"  border:1px solid var(--dim);\n"
"  padding:10px;\n"
"  font-family:var(--mono);\n"
"  font-size:11px;\n"
"  height:120px;\n"
"  overflow-y:auto;\n"
"  color:var(--dim);\n"
"  margin-top:12px;\n"
"  line-height:1.5;\n"
"}\n"
"footer{\n"
"  text-align:center;\n"
"  color:var(--dim);\n"
"  font-size:10px;\n"
"  margin-top:24px;\n"
"  padding:14px 0;\n"
"  border-top:1px solid var(--dim);\n"
"  letter-spacing:1.5px;\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <div>\n"
"    <h1>// DSP32-S3 // <span class=\"badge\">OTA UPDATE</span></h1>\n"
"  </div>\n"
"  <a href=\"/\"><button>[ &lt; DASHBOARD ]</button></a>\n"
"</header>\n"
"\n"
"<div class=\"section\">\n"
"  <div class=\"sec-title\">// 01. FIRMWARE &amp; PARTITION STATUS //</div>\n"
"  <div class=\"info-grid\">\n"
"    <div class=\"info-item\"><div class=\"info-lbl\">RUNNING SLOT</div><b id=\"info-running\" class=\"badge\">loading...</b></div>\n"
"    <div class=\"info-item\"><div class=\"info-lbl\">TARGET UPDATE SLOT</div><b id=\"info-target\" class=\"badge\">loading...</b></div>\n"
"    <div class=\"info-item\"><div class=\"info-lbl\">CURRENT VERSION</div><b id=\"info-ver\">...</b></div>\n"
"    <div class=\"info-item\"><div class=\"info-lbl\">LITTLEFS CACHE SPACE</div><b id=\"info-fs\">...</b></div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"section\">\n"
"  <div class=\"sec-title\">// 02. SELECT NEW FIRMWARE (.BIN) //</div>\n"
"  <input type=\"file\" id=\"file-input\" accept=\".bin\" style=\"display:none\">\n"
"  <div class=\"drop-zone\" id=\"drop-zone\" onclick=\"document.getElementById('file-input').click()\">\n"
"    <div style=\"font-size:20px;margin-bottom:6px\">[ ^ ]</div>\n"
"    <div style=\"font-weight:700;margin-bottom:4px\" id=\"file-label\">CLICK TO SELECT OR DRAG &amp; DROP FIRMWARE_OTA.BIN</div>\n"
"    <div style=\"color:var(--dim);font-size:10px\">Binary will be cached in LittleFS, verified, and flashed to opposite OTA slot.</div>\n"
"  </div>\n"
"  <div style=\"margin-top:14px;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px\">\n"
"    <span id=\"file-meta\" style=\"font-family:var(--mono);color:var(--dim);font-size:11px\">No file selected</span>\n"
"    <button id=\"btn-upload\" disabled onclick=\"startOTA()\">[ START OTA UPDATE ]</button>\n"
"  </div>\n"
"  <div class=\"progress-wrap\" id=\"progress-wrap\">\n"
"    <div class=\"progress-bar\" id=\"progress-bar\"></div>\n"
"  </div>\n"
"  <div id=\"status-text\" style=\"font-size:11px;margin-top:8px;color:var(--fg)\"></div>\n"
"  <div class=\"log-box\" id=\"log-box\">[Ready] Select a firmware binary (.bin) to begin update.</div>\n"
"</div>\n"
"\n"
"<footer>\n"
"  // ESP32-S3 SUPERMINI &bull; FAIL-SAFE DUAL OTA &bull; LITTLEFS CACHED FLASH //\n"
"</footer>\n"
"\n"
"<script>\n"
"let selectedFile = null;\n"
"\n"
"function log(msg) {\n"
"  const b = document.getElementById('log-box');\n"
"  if (!b) return;\n"
"  const t = new Date().toLocaleTimeString();\n"
"  b.innerHTML += `\\n[${t}] ${msg}`;\n"
"  b.scrollTop = b.scrollHeight;\n"
"}\n"
"\n"
"function loadStatus() {\n"
"  fetch('/api/ota/status')\n"
"    .then(r => r.json())\n"
"    .then(d => {\n"
"      document.getElementById('info-running').innerText = d.running_partition || 'ota_0';\n"
"      document.getElementById('info-target').innerText = d.target_partition || 'ota_1';\n"
"      document.getElementById('info-ver').innerText = (d.version || '0.1') + ' (' + (d.compile_date || '') + ')';\n"
"      const freeMb = ((d.littlefs_free_bytes || 0) / (1024*1024)).toFixed(2);\n"
"      document.getElementById('info-fs').innerText = freeMb + ' MB available';\n"
"    }).catch(e => log('Failed to load OTA status: ' + e));\n"
"}\n"
"\n"
"const dropZone = document.getElementById('drop-zone');\n"
"const fileInput = document.getElementById('file-input');\n"
"const btnUpload = document.getElementById('btn-upload');\n"
"\n"
"['dragenter','dragover'].forEach(n => dropZone.addEventListener(n, e => { e.preventDefault(); dropZone.classList.add('hover'); }));\n"
"['dragleave','drop'].forEach(n => dropZone.addEventListener(n, e => { e.preventDefault(); dropZone.classList.remove('hover'); }));\n"
"dropZone.addEventListener('drop', e => {\n"
"  if (e.dataTransfer.files.length > 0) handleFile(e.dataTransfer.files[0]);\n"
"});\n"
"fileInput.addEventListener('change', e => {\n"
"  if (e.target.files.length > 0) handleFile(e.target.files[0]);\n"
"});\n"
"\n"
"function handleFile(f) {\n"
"  if (!f.name.endsWith('.bin')) {\n"
"    alert('Please select a valid ESP32 binary (.bin) file');\n"
"    return;\n"
"  }\n"
"  selectedFile = f;\n"
"  const kb = Math.round(f.size / 1024);\n"
"  document.getElementById('file-label').innerText = f.name;\n"
"  document.getElementById('file-meta').innerText = `File: ${f.name} (${kb} KB)`;\n"
"  btnUpload.disabled = false;\n"
"  log(`Selected file: ${f.name} (${kb} KB)`);\n"
"}\n"
"\n"
"function startOTA() {\n"
"  if (!selectedFile) return;\n"
"  btnUpload.disabled = true;\n"
"  fileInput.disabled = true;\n"
"  const wrap = document.getElementById('progress-wrap');\n"
"  const bar = document.getElementById('progress-bar');\n"
"  const st = document.getElementById('status-text');\n"
"  wrap.style.display = 'block';\n"
"  bar.style.width = '0%';\n"
"  st.innerText = '// Phase 1/3: Uploading & caching to LittleFS... //';\n"
"  log('Starting upload of ' + selectedFile.name + '...');\n"
"\n"
"  const xhr = new XMLHttpRequest();\n"
"  xhr.open('POST', '/api/ota/upload', true);\n"
"  xhr.setRequestHeader('Content-Type', 'application/octet-stream');\n"
"  xhr.setRequestHeader('X-File-Size', selectedFile.size);\n"
"\n"
"  xhr.upload.onprogress = function(e) {\n"
"    if (e.lengthComputable) {\n"
"      const pct = Math.round((e.loaded / e.total) * 100);\n"
"      bar.style.width = pct + '%';\n"
"      st.innerText = `// Phase 1/3: Uploading & caching (${pct}% - ${Math.round(e.loaded/1024)}/${Math.round(e.total/1024)} KB) //`;\n"
"    }\n"
"  };\n"
"\n"
"  xhr.onload = function() {\n"
"    if (xhr.status === 200) {\n"
"      try {\n"
"        const res = JSON.parse(xhr.responseText);\n"
"        if (res.status === 'ok') {\n"
"          bar.style.width = '100%';\n"
"          st.innerText = '// Phase 3/3: Success! Rebooting into new version... //';\n"
"          log('OTA flashing complete! Rebooting device...');\n"
"          let count = 6;\n"
"          setInterval(() => {\n"
"            count--;\n"
"            if (count > 0) {\n"
"              st.innerText = `// Rebooting... Returning to dashboard in ${count}s //`;\n"
"            } else {\n"
"              window.location.href = '/';\n"
"            }\n"
"          }, 1000);\n"
"        } else {\n"
"          st.innerText = '// Error: ' + (res.message || 'Update failed') + ' //';\n"
"          log('Error: ' + res.message);\n"
"          btnUpload.disabled = false;\n"
"        }\n"
"      } catch(err) {\n"
"        st.innerText = '// Server response parse error //';\n"
"        log('Response error: ' + xhr.responseText);\n"
"        btnUpload.disabled = false;\n"
"      }\n"
"    } else {\n"
"      st.innerText = `// Upload failed with HTTP ${xhr.status} //`;\n"
"      log(`HTTP Error ${xhr.status}: ${xhr.responseText}`);\n"
"      btnUpload.disabled = false;\n"
"    }\n"
"  };\n"
"\n"
"  xhr.onerror = function() {\n"
"    st.innerText = '// Network error during upload //';\n"
"    log('Network error occurred');\n"
"    btnUpload.disabled = false;\n"
"  };\n"
"\n"
"  xhr.send(selectedFile);\n"
"}\n"
"\n"
"window.onload = loadStatus;\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif /* _OTA_UI_HTML_H_ */
